#!/bin/bash
BOARD="orangepi_pc2_defconfig"
UBOOT="https://gitlab.denx.de/u-boot/u-boot.git"
URL_BL31="https://github.com/ARM-software/arm-trusted-firmware.git"
DATE=$(date +'%Y-%m-%d-%H-%M-%S')
WORK_DIR="${HOME}/work"
OUT_DIR="${HOME}/uboot-$DATE"
if ! [ -d $WORK_DIR ] ; then 
    mkdir -p $WORK_DIR
fi
mkdir -p $OUT_DIR && cd $WORK_DIR
if ! [ -d u-boot ] ; then
    git clone $UBOOT 
else cd u-boot && git pull && make clean && cd ..
fi
if ! [ -d arm-trusted-firmware ] ; then
    git clone $URL_BL31
else cd arm-trusted-firmware && git pull && make clean && cd ..
fi
cd arm-trusted-firmware && \
make PLAT=sun50i_a64 DEBUG=1 bl31 && \
export BL31=$(pwd)/build/sun50i_a64/debug/bl31.bin && \
cd ../u-boot/ && make $BOARD && make && \
cp u-boot-sunxi-with-spl.bin $OUT_DIR/u-boot-$DATE.bin
if ! [ -f $HOME/sync.conf ] ; then
    echo "Синхронизация не возможна, отсутствует файл $HOME/sync.conf"
    exit
else source $HOME/sync.conf && \
     ping $HOST -c 5 -w 10 &>/dev/null
     TEST_HOST=$?
    if [[ $TEST_HOST -eq 0 ]] ; then
        echo "Введите пароль от $USR@$HOST для отправки файла u-boot-$DATE.bin"
        rsync -zavP "-e ssh" $OUT_DIR/u-boot-$DATE.bin $USR@$HOST:$DIR
    else
        echo "Удаленный сервер $HOST не доступен для синхронизации $OUT_DIR/u-boot-$DATE.bin"
    fi
fi